config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :categories do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks, dependent: :destroy
  belongs_to :user

  validates :name, presence: true, uniqueness: { scope: :user }
  validates :details, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category

  validates :name, presence: true, uniqueness: { scope: :category }
  validates :details, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = current_user.categories.order('created_at DESC')
  end

  def new
    @category = current_user.categories.build
  end

  def create
    @category = current_user.categories.build(category_params)

    if @category.valid?
    @category.save
    redirect_to categories_path
    flash[:notice] = 'Category created!'
    else
      redirect_to new_category_path, alert: @category.errors.full_messages.first
    end
  end

  def show
    @category = current_user.categories.find(params[:id])
  end

  def edit
    @category = current_user.categories.find(params[:id])
  end

  def update
    @category = current_user.categories.find(params[:id])

    if @category.update(category_params)
      @category.save
      redirect_to categories_path, notice: 'Category successfully updated.'

    else
      redirect_to edit_category_path, alert: @category.errors.full_messages.first
    end
  end

  def destroy
    @category = current_user.categories.find(params[:id])
    @category.destroy
    redirect_to categories_path, notice: 'Category successfully deleted.'
  end

  private

  def category_params
    params.require(:category).permit(:name, :details)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  before_action :get_category

  def index
    @categories = current_user.categories.all if current_user != nil
  end

  private
  def get_category
    @categories = current_user.categories.all
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :get_category

  def index
    @tasks = @category.tasks.all
    redirect_to category_path(@category)
  end

  def new
    @task = @category.tasks.build
  end

  def create
    @task = @category.tasks.build(task_params)
    if @task.valid?
      @task.save
      redirect_to category_task_path
      flash[:notice] = 'Task created!'
    else
      redirect_to category_path(@category), alert: @task.errors.full_messages.first
    end
  end

  def show
    @task = @category.tasks.find(params[:id])
  end

  def edit
    @task = @category.tasks.find(params[:id])
  end

  def update
    @task = @category.tasks.find(params[:id])

    if @task.update(task_params)
      @task.save
      redirect_to category_tasks_path(@category)
      flash[:notice] = 'Task successfully updated.'
    else
      redirect_to edit_category_task_path(@category), alert: @task.errors.full_messages.first
    end
  end

  def destroy
    @task = @category.tasks.find(params[:id])
    @task.destroy
    redirect_to category_tasks_path, notice: 'Task successfully deleted.'
  end

  private

  def get_category
    @category = current_user.categories.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :details, :deadline, :category_id, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
 <div class="container bg-light" style="margin-top: 100px; width: 50vw">
  <div class="row">
		<div class="span4 offset4 well">
      <div class="container" style="margin-bottom: 20px; margin-top: 10px;">
      <%= link_to 'Back', categories_path, class:"btn btn-secondary btn-lg float-end" %>
      <h1>Categories</h1>
      </div>
 
 <%= form_with model: category do |f| %>
  <div class="input-group mb-3">
    <%= f.label :name, class:"input-group-text" %>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="input-group mb-3">
    <%= f.label :details, class:"input-group-text" %>
    <%= f.text_area :details, class:"form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class:"btn btn-danger btn-lg btn-block" %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render "form", category: @category %>

app/views/categories/index.html.erb
<div class="container" style="margin-top: 100px;">
		<div class="row">
			<div class="col-md-10">
      <div class="container" style="margin-bottom: 20px; margin-top: 10px;">
      <%= link_to 'New Category', new_category_path, class:"btn btn-secondary btn-lg float-end" %>
      <h1>Categories</h1>
      </div>
				<div class="table">
					<table class="table table-striped" style="border: 1px solid #d3d3d3;">
            <thead>
              <tr>
                <th>Name</th>
                <th>Details</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @categories.each do |category| %>
            <tr>
              <td><%= category.name %></td>
              <td><%= category.details %></td>
              <td>
                  <%= link_to 'View', category %> | <%= link_to 'Edit', edit_category_path(category) %>
              </td>
            </tr>
          <% end %>
             </tbody>
          </table>
        </div>
      </div>
		</div>
	</div>

app/views/categories/new.html.erb
<h1>Create New Category</h1>

<%= render "form", category: @category %>

app/views/categories/show.html.erb
<div class="container" style="margin-top: 100px; width: 80vw">
		<div class="row justify-content-md-center">
			<div class="col-md-8">
      <div class="container" style="margin-bottom: 20px; margin-top: 10px;">
      <%= link_to 'Edit Category', edit_category_path, class:"btn btn-secondary btn-lg float-end" %>
      <h1>View Categories</h1>
      </div>
				<div class="table">
					<table class="table table-striped" style="border: 1px solid #d3d3d3;">
            <thead>
              <tr>
                <th>Name</th>
                <th>Details</th>
              </tr>
            </thead>
            <tbody>
            <tr>
              <td><%= @category.name %></td>
              <td><%= @category.details %></td>
            </tr>
             </tbody>
          </table>
        </div>
      </div>
		</div>
	</div>

app/views/home/index.html.erb
<% if user_signed_in? %>
<div class="container-fluid" style="margin-top: 70px;">
<h1 class="text-center"><%= "Things I Got To Do Today! #{Date.today.to_s(:long)}" %></h1>



<div class="container" style="margin-top: 100px;">
  <div class="row">
  	<div class="col-md-12">
      <div class="container" style="margin-bottom: 20px; margin-top: 10px;"><%= link_to "Create Category", new_category_path, class:"btn btn-info btn-lg float-end" %>
      <%= link_to 'Create Task', new_category_task_path(:category_id), class:"btn btn-secondary btn-lg float-end" %>
      <h1>Task yolo!</h1>
      </div>
				<div class="table">
					<table class="table table-striped" style="border: 1px solid #d3d3d3;">
            <thead>
              <tr>
                <th>Name</th>
                <th>Details</th>
                <th>Deadline</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @categories.each do |category| %>
              <% category.tasks.all.sort_by { |c| c["created_at"] }.each do |task| %>
              
              <tr>
                <td style="width:10%"><%= task.name %></td>
                <td style="width:10%"><%= task.details %></td>
                <td style="width:10%"><%= task.deadline.to_s %></td>
                <td style="width:10%"><%= link_to "Edit" %>
              | <%= link_to "Delete",  method: :delete, data: { confirm: "Are you sure?" } %> 
                </td>
              </tr>
              <% end %>
             <% end %> 
            </tbody>
          </table>
        </div>
      </div>
		</div>
      
    
  <% end %>
	</div>

<% if !user_signed_in? %>
<div class="container-fluid" style="margin-top: 60px;">
<%= render 'partials/carousel' %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TGITDT</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    

<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
  rel="stylesheet"
/>
<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  rel="stylesheet"
/>
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
  rel="stylesheet"
/>
</head>

  <body>
    <%= render 'partials/header' %>
    <div class="container">
      <%= render 'partials/messages'%>
    </div>

    <%= yield %>

    <%= render 'partials/footer' %>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> 
  </body>
</html>

app/views/partials/_carousel.html.erb
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://images.pexels.com/photos/7213439/pexels-photo-7213439.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=400&w=1260" class="d-block w-100 img-responsive fixed-height" alt="...">
      <div class="carousel-caption d-none d-md-block" style="
      background: linear-gradient(
        45deg,
        rgba(29, 236, 197, 0.7),
        rgba(91, 14, 214, 0.7) 100%
      );
    ">
        <h2 class="text-dark">Got tons of things to do?</h2>
        <h3 class="text-dark">Our app makes todos fun</h3>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://images.pexels.com/photos/7580842/pexels-photo-7580842.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=400&w=1260" class="d-block w-100 img-responsive fixed-height" alt="...">
      <div class="carousel-caption d-none d-md-block" style="
      background: linear-gradient(
        45deg,
        rgba(29, 236, 197, 0.7),
        rgba(91, 14, 214, 0.7) 100%
      );
    ">
        <h2 class="text-dark">Second slide label</h2>
        <h3 class="text-dark">Some representative placeholder content for the second slide.</h3>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://images.pexels.com/photos/131979/pexels-photo-131979.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=400&w=1260" class="d-block w-100 img-responsive fixed-height" alt="...">
      <div class="carousel-caption d-none d-md-block" style="
      background: linear-gradient(
        45deg,
        rgba(29, 236, 197, 0.7),
        rgba(91, 14, 214, 0.7) 100%
      );
    ">
        <h2 class="text-dark">Third slide label</h2>
        <h3 class="text-dark">Some representative placeholder content for the third slide.</h3>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/partials/_footer.html.erb
<footer class="bg-dark text-center text-white fixed-bottom">
  <!-- Grid container -->
  <div class="container">
    <!-- Section: Form -->
    <section class="">
      <form action="">
        <!--Grid row-->
        <div class="row d-flex justify-content-center">

        </div>
        <!--Grid row-->
      </form>
    </section>
    <!-- Section: Form -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3">
    © 2021 TGITDT Copyright:
    <a class="text-white" href="https://jaren.cudilla.net/">Jaren Cudilla</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/partials/_header.html.erb
<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <!-- Container wrapper -->
  <div class="container">
    <!-- Navbar brand -->
    <%= link_to "TGITDT", root_path, class: "navbar-brand" %>
    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarButtonsExample"
      aria-controls="navbarButtonsExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <% if user_signed_in? %>
    <div class="collapse navbar-collapse" id="navbarButtonsExample">
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item ">
          <%= link_to 'Dashboard', categories_path, class:"text-light"%>
        </li>
      </ul>
      <!-- Left links -->
      <div class="d-flex align-items-center">
          <%= link_to "Sign out", destroy_user_session_path, protocol: 'https', method: :delete, class:"btn btn-info px-3 me-2" %>
      </div>
    </div>
      <% else %>
    <div class="collapse navbar-collapse" id="navbarButtonsExample">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item ">
        ...
        </li>
      </ul>
      <div class="d-flex align-items-center">
          <%= link_to "Login", new_user_session_path, class:"btn btn-secondary px-3 me-2" %> 
          <%= link_to "Sign up", new_user_registration_path, class:"btn btn-danger me-3" %> 
        <a
          class="btn btn-dark px-3"
          href="https://github.com/jarencudilla/Rails-Todo-App---with-Devise"
          role="button"
          ><i class="fab fa-github"></i
        ></a>
      </div>
    </div>
    <% end %>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->

app/views/partials/_messages.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 60px;">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 60px;">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>  

app/views/tasks/_form.html.erb
 <%= form_with model: [category, task] do |f| %>
 <div class="container bg-light" style="margin-top: 100px; width: 50vw">
  <div class="row">
		<div class="span4 offset4 well">
      <div class="container" style="margin-bottom: 20px; margin-top: 10px;">
      <%= link_to 'Back', category_tasks_path, class:"btn btn-secondary btn-lg float-end" %>
      <h1>Task</h1>
      </div>

    <div class="card-body">
    
    
    <div class="input-group mb-3">
    <%= f.label :name, class:"input-group-text" %>
    <%= f.text_field :name, class:"form-control" %>
    </div>

    <div class="input-group mb-3">
    <%= f.label :details, class:"input-group-text" %>
    <%= f.text_area :details, class:"form-control" %>
    </div>

    <div class="form-group" style="margin-bottom: 20px; margin-top: 10px;">
    <%= f.select :category_id, Category.all.map {|c| [c.name, c.id]} %>
    </div>

    <div class="input-group mb-3">
    <%= f.label :deadline, class:"input-group-text" %>
    <%= f.datetime_local_field :deadline, class:"datepicker" %>
    </div>

    <div class="form-check" style="margin-bottom: 10px;">
    <%= f.label :completed, class:"form-check-label" %>
    <%= f.check_box :finish, class:"form-check-input" %>
    </div>

    <%= f.submit "Create Task", class: "btn btn-primary btn-lg btn-block" %>


    </div>
  </div>
</div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render "form" %>

app/views/tasks/new.html.erb
<h1>Create New Task</h1>

<%= render "form", task: @task, category: @category %>

app/views/tasks/show.html.erb
<div class="container" style="margin-top: 100px;">
  <div class="row">
  	<div class="col-md-10">
      <div class="container" style="margin-bottom: 20px; margin-top: 10px;">
      <%= link_to 'Create Task', new_category_task_path(:category_id), class:"btn btn-secondary btn-lg float-end" %>
      <h1>Yolo!</h1>
      </div>
				<div class="table">
        <% @categories.sort.each do |category| %>
        
					<table class="table table-striped" style="border: 1px solid #d3d3d3;">
            <thead>
              <tr>
                <th>Name</th>
                <th>Details</th>
                <th>Deadline</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% category.tasks.all.sort_by { |c| c["created_at"] }.each do |task| %>
            <tr>
              <td style="width:10%"><%= task.name %></td>
              <td style="width:10%"><%= task.details %></td>
              <td style="width:10%"><%= task.deadline.to_s %></td>
              <td style="width:10%"><%= link_to "Edit", edit_category_task_path(@category, @task) %>
              | <%= link_to "Delete", category_task_path(@category, task), method: :delete, data: { confirm: "Are you sure?" } do %>
              <% end %>  
              </td>
            </tr>
              <% end %>
             </tbody>
          </table>
        </div>
      </div>
		</div>
    <% end %>
  <% end %>
	</div>